---

hostname_fqdn: "{% if ansible_os_family == 'Debian' %}{{ inventory_hostname.split('.') | first }}{% else %}{{ inventory_hostname }}{% endif %}"
hosts_enable_localhost: yes
hosts_extra_localhosts: []
project_mosquitto_bind_address: "{{ ansible_eth0.ipv4.address }}"
