---
os: linux
dist: bionic
language: ruby
rvm:
  - 2.6
cache:
  directories:
    - $HOME/.vagrant.d/boxes/
  bundler: true
  pip: true

addons:
  chrome: stable
  apt:
    update: true
    packages:
      - python-pip
      - curl

      # for aspell
      - aspell
      - aspell-en

before_install:
  - pyenv global 3.7

  # Use bundler 2.x
  - yes | gem update --system --force
  - gem install bundler
  - wget https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
  - sudo dpkg -i vagrant_2.2.9_x86_64.deb
  - vagrant --version

  # for virtualbox
  - sudo apt-get install "linux-headers-`uname -r`"
  - wget -q https://github.com/trombik/ansible-role-sensu_go_backend/releases/download/1.4.0/oracle_vbox_2016.asc -O - | sudo apt-key add -
  - sudo add-apt-repository -y "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian `lsb_release -cs` contrib"
  - sudo apt-get update
  - sudo apt-get install virtualbox-6.1

install:
  - npm install

  # XXX without this, pip3 fails with
  # `The `pip3' command exists in these Python versions:`
  - pip3 install --user yamllint ansible
  - bundle install --path=vendor/bundle --with development

  # Check versions
  - ansible --version

script:
  - bundle exec rubocop --display-style-guide --extra-details --display-cop-names
  - node node_modules/markdownlint-cli/markdownlint.js .
  - yamllint -c .yamllint.yml .
  - bundle exec rake test
